VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "MuestraEngine"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'---------------------------------------------------------------------------------------
' Module    : MuestraEngine
' Author    : Charly
' Date      : 23/04/2012
' Purpose   :
'---------------------------------------------------------------------------------------

Option Explicit

