VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Dupla"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
' *============================================================================*
' *
' *     Fichero    : Dupla.cls
' *
' *     Autor      : Carlos Almela Baeza
' *     Creación   : do., 17/mar/2019 09:32:55
' *     Versión    : 1.0
' *     Propósito  : Almacenar una dupla de datos representada por su clave y
' *                  valor
' *============================================================================*
Option Explicit
'------------------------------------------------------------------------------*
' Procedimiento  : Key
' Fecha          : 17/mar/2019
' Propósito      : Clave de la Dupla
'------------------------------------------------------------------------------*
'
Public Key As String
'------------------------------------------------------------------------------*
' Procedimiento  : Value
' Fecha          : 17/mar/2019
' Propósito      : Volar de la Dupla
'------------------------------------------------------------------------------*
'
Public Value As Variant
' *===========(EOF): Dupla.cls
