VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Apuestas"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'---------------------------------------------------------------------------------------
' Module    : Apuestas
' Author    : CHARLY
' Date      : dom, 12/oct/2014 00:52:08
' Purpose   : Colección de apuestas
'---------------------------------------------------------------------------------------
'
Option Explicit
Option Base 0

