VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ApuestasEngine"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'---------------------------------------------------------------------------------------
' Module    : ApuestasEngine
' Author    : CHARLY
' Date      : dom, 12/oct/2014 00:51:44
' Purpose   : Motor de generación de apuestas
'---------------------------------------------------------------------------------------
'
Option Explicit
Option Base 0

